import type { Donation } from "../types";

export const SEED_DONATIONS: Donation[] = [
  {
    id: "d1",
    name: "Jean-Paul Mutombo",
    anonymous: false,
    amount: 50,
    currency: "USD",
    method: "mobile_money",
    date: "2026-04-27",
    category: "dime",
    notes: "",
  },
  {
    id: "d2",
    name: "Anonyme",
    anonymous: true,
    amount: 200000,
    currency: "CDF",
    method: "especes",
    date: "2026-04-27",
    category: "offrande",
    notes: "",
  },
  {
    id: "d3",
    name: "Famille Ilunga",
    anonymous: false,
    amount: 100,
    currency: "USD",
    method: "virement",
    date: "2026-04-26",
    category: "construction",
    notes: "Don spécial pour le nouveau temple",
  },
  {
    id: "d4",
    name: "Rachel Ntumba",
    anonymous: false,
    amount: 25,
    currency: "USD",
    method: "mobile_money",
    date: "2026-04-25",
    category: "mission",
    notes: "Contribution MGRN",
  },
  {
    id: "d5",
    name: "Anonyme",
    anonymous: true,
    amount: 500000,
    currency: "CDF",
    method: "especes",
    date: "2026-04-20",
    category: "don_special",
    notes: "",
  },
  {
    id: "d6",
    name: "Pasteur Adjoint",
    anonymous: false,
    amount: 30,
    currency: "USD",
    method: "mobile_money",
    date: "2026-04-20",
    category: "dime",
    notes: "",
  },
  {
    id: "d7",
    name: "Groupe Mamans Deborah",
    anonymous: false,
    amount: 75,
    currency: "USD",
    method: "especes",
    date: "2026-04-13",
    category: "offrande",
    notes: "Collecte de la réunion mensuelle",
  },
  {
    id: "d8",
    name: "Daniel Tshilombo",
    anonymous: false,
    amount: 200,
    currency: "USD",
    method: "virement",
    date: "2026-04-13",
    category: "construction",
    notes: "",
  },
  {
    id: "d9",
    name: "Anonyme",
    anonymous: true,
    amount: 15,
    currency: "USD",
    method: "mobile_money",
    date: "2026-04-06",
    category: "dime",
    notes: "",
  },
  {
    id: "d10",
    name: "Famille Beya",
    anonymous: false,
    amount: 1000000,
    currency: "CDF",
    method: "especes",
    date: "2026-03-30",
    category: "dime",
    notes: "",
  },
  {
    id: "d11",
    name: "Association Papas Salomon",
    anonymous: false,
    amount: 50,
    currency: "USD",
    method: "especes",
    date: "2026-03-30",
    category: "offrande",
    notes: "",
  },
  {
    id: "d12",
    name: "Anonyme",
    anonymous: true,
    amount: 300,
    currency: "USD",
    method: "virement",
    date: "2026-03-15",
    category: "mission",
    notes: "Diaspora — don pour l'évangélisation",
  },
];
