import type { EventItem } from "../types";

export const SEED_EVENTS: EventItem[] = [
  {
    id: "e1",
    date: "2026-05-25",
    title: "Conférence MGRN — Mission, Guérison, Restauration des Nations",
    desc: "Trois soirées de réveil avec la fanfare et les chorales unies. Orateurs invités de toute la RDC.",
    location: "Temple central Mpasa",
    image: "/images/cba-worship.png",
    tag: "À venir",
  },
  {
    id: "e2",
    date: "2026-06-15",
    title: "Convention nationale 40 ans",
    desc: "Célébration grandiose des 40 ans de l'œuvre nationale. Tous les assemblées réunies.",
    location: "Limete — De Bonhomme n°2",
    image: "/images/cba-community.png",
    tag: "À venir",
  },
  {
    id: "e3",
    date: "2026-07-04",
    title: "Retraite spirituelle — Jeunesse Timothée",
    desc: "Week-end de formation et de rafraîchissement spirituel pour les jeunes de l'assemblée.",
    location: "Camp chrétien de Kinsuka",
    image: "/images/cba-bible.png",
    tag: "À venir",
  },
  {
    id: "e4",
    date: "2026-04-20",
    title: "Dimanche de Pâques — Culte de Résurrection",
    desc: "Grande célébration pascale avec les chorales, la fanfare et un repas communautaire.",
    location: "Temple central Mpasa",
    image: "/images/cba-worship.png",
    tag: "Passé",
  },
  {
    id: "e5",
    date: "2026-03-22",
    title: "Retraite des Mamans Deborah",
    desc: "Week-end d'intercession et de jeûne pour les mères de l'assemblée.",
    location: "Mpasa Mikonga",
    image: "/images/cba-bible.png",
    tag: "Passé",
  },
  {
    id: "e6",
    date: "2026-02-14",
    title: "Journée de l'Amour Agapé",
    desc: "Rencontre fraternelle et partage autour de l'amour chrétien.",
    location: "Temple central Mpasa",
    image: "/images/cba-community.png",
    tag: "Passé",
  },
  {
    id: "e7",
    date: "2026-08-15",
    title: "Camp d'évangélisation MGRN",
    desc: "Mission d'évangélisation dans les quartiers périphériques de Kinshasa.",
    location: "Divers quartiers — Kinshasa",
    image: "/images/cba-worship.png",
    tag: "À venir",
  },
];
