import type { Member } from "../types";

export const SEED_MEMBERS: Member[] = [
  {
    id: "n1",
    firstName: "Joëlle",
    lastName: "Mbuyi",
    phone: "+243 81 000 0001",
    email: "joelle.mbuyi@example.com",
    quartier: "Mpasa I",
    structure: "Mamans Deborah",
    baptized: true,
    notes: "",
    createdAt: "2026-04-28T10:00:00Z",
  },
  {
    id: "n2",
    firstName: "David",
    lastName: "Ilunga",
    phone: "+243 82 000 0002",
    email: "david.ilunga@example.com",
    quartier: "Mikonga",
    structure: "Jeunesse Timothée",
    baptized: true,
    notes: "Guitariste — intéressé par la chorale",
    createdAt: "2026-04-25T16:30:00Z",
  },
  {
    id: "n3",
    firstName: "Sarah",
    lastName: "Beya",
    phone: "+243 89 000 0003",
    email: "",
    quartier: "Tala Ngai",
    structure: "Les Amis de Jésus",
    baptized: false,
    notes: "Catéchumène — baptême prévu en juin",
    createdAt: "2026-04-22T09:10:00Z",
  },
  {
    id: "n4",
    firstName: "Emmanuel",
    lastName: "Kasongo",
    phone: "+243 97 000 0004",
    email: "emma.kasongo@example.com",
    quartier: "Mpasa II",
    structure: "Papas Salomon",
    baptized: true,
    notes: "",
    createdAt: "2026-04-20T11:45:00Z",
  },
  {
    id: "n5",
    firstName: "Patience",
    lastName: "Mukeba",
    phone: "+243 81 000 0005",
    email: "patience.m@example.com",
    quartier: "Mikonga",
    structure: "Mamans Deborah",
    baptized: true,
    notes: "Ancienne membre revenue après 2 ans",
    createdAt: "2026-04-18T08:20:00Z",
  },
  {
    id: "n6",
    firstName: "Josué",
    lastName: "Kalombo",
    phone: "+243 82 000 0006",
    email: "",
    quartier: "Tala Ngai",
    structure: "Jeunesse Timothée",
    baptized: false,
    notes: "",
    createdAt: "2026-04-15T14:00:00Z",
  },
  {
    id: "n7",
    firstName: "Rachel",
    lastName: "Ntumba",
    phone: "+243 99 000 0007",
    email: "rachel.ntumba@example.com",
    quartier: "Mpasa I",
    structure: "Chorale Hosanna",
    baptized: true,
    notes: "Soprano — chef de voix",
    createdAt: "2026-04-10T09:30:00Z",
  },
];
