import type { Schedule } from "../types";

export const SEED_SCHEDULES: Schedule[] = [
  {
    id: "sc1",
    dayOfWeek: 0,
    startTime: "09:00",
    endTime: "12:00",
    title: "Culte d'Adoration et de Célébration",
    location: "Temple central Mpasa",
    description: "Culte principal dominical avec louange, prédication et sainte cène (premier dimanche du mois).",
    recurring: true,
  },
  {
    id: "sc2",
    dayOfWeek: 1,
    startTime: "09:00",
    endTime: "16:00",
    title: "Réunion des Mamans Deborah",
    location: "Salle annexe — Mpasa",
    description: "Rencontre hebdomadaire des mères de l'assemblée : prière, étude biblique et soutien mutuel.",
    recurring: true,
  },
  {
    id: "sc3",
    dayOfWeek: 2,
    startTime: "17:00",
    endTime: "19:00",
    title: "Culte d'Enseignements",
    location: "Temple central Mpasa",
    description: "Enseignement biblique approfondi et questions-réponses.",
    recurring: true,
  },
  {
    id: "sc4",
    dayOfWeek: 3,
    startTime: "09:00",
    endTime: "12:00",
    title: "Prière d'Autel",
    location: "Temple central Mpasa",
    description: "Intercession collective, prière de guerre spirituelle et louange spontanée.",
    recurring: true,
  },
  {
    id: "sc5",
    dayOfWeek: 4,
    startTime: "17:00",
    endTime: "19:00",
    title: "Culte d'Enseignements",
    location: "Temple central Mpasa",
    description: "Enseignement biblique approfondi — suite du mardi.",
    recurring: true,
  },
  {
    id: "sc6",
    dayOfWeek: 6,
    startTime: "14:00",
    endTime: "16:30",
    title: "Répétition — Chorale Hosanna",
    location: "Salle musicale",
    description: "Répétition hebdomadaire de la chorale de l'assemblée.",
    recurring: true,
  },
  {
    id: "sc7",
    dayOfWeek: 6,
    startTime: "09:00",
    endTime: "12:00",
    title: "Jeunesse Timothée — Formation",
    location: "Salle jeunesse",
    description: "Formation spirituelle et activités pour les jeunes de 15 à 35 ans.",
    recurring: true,
  },
];
