import type { Sermon } from "../types";

export const SEED_SERMONS: Sermon[] = [
  {
    id: "s1",
    title: "Le Peuple d'Autel",
    speaker: "Pasteur Principal",
    date: "2026-04-27",
    series: "Les 4 Piliers",
    duration: "52 min",
    link: "",
    published: true,
  },
  {
    id: "s2",
    title: "L'Alliance qui Transforme",
    speaker: "Pasteur Adjoint",
    date: "2026-04-20",
    series: "Les 4 Piliers",
    duration: "48 min",
    link: "",
    published: true,
  },
  {
    id: "s3",
    title: "MGRN — La Vision en Marche",
    speaker: "Pasteur Principal",
    date: "2026-04-13",
    series: "Vision MGRN",
    duration: "61 min",
    link: "",
    published: true,
  },
  {
    id: "s4",
    title: "Marche dans la Lumière de Dieu",
    speaker: "Pasteur Principal",
    date: "2026-04-06",
    series: "Vie Chrétienne",
    duration: "45 min",
    link: "",
    published: true,
  },
  {
    id: "s5",
    title: "La Foi qui Déplace les Montagnes",
    speaker: "Ancien Jean-Pierre Mbala",
    date: "2026-03-30",
    series: "La Foi",
    duration: "50 min",
    link: "",
    published: true,
  },
  {
    id: "s6",
    title: "L'Amour de Dieu Sans Condition",
    speaker: "Pasteur Adjoint",
    date: "2026-03-23",
    series: "L'Évangile",
    duration: "42 min",
    link: "",
    published: false,
  },
  {
    id: "s7",
    title: "Peuple de Célébration",
    speaker: "Pasteur Principal",
    date: "2026-03-16",
    series: "Les 4 Piliers",
    duration: "55 min",
    link: "",
    published: true,
  },
  {
    id: "s8",
    title: "Le Peuple de Mission",
    speaker: "Pasteur Principal",
    date: "2026-03-09",
    series: "Les 4 Piliers",
    duration: "58 min",
    link: "",
    published: true,
  },
];
